export const data = [
    {
        heading: "Blogging App",
        tech: "NodeJS, express, EJS, CSS",
        description: "It's a application to create blogs. application contains funcalities like add blog, edit and delete blogs.", 
        code: "https://github.com/ashokkhandhar/blogging-app",
        live: "https://blogger-app-igy0.onrender.com/",
    },
    {
        heading: "Todo App",
        tech: "NodeJS, express, EJS, CSS",
        description: "It's a application of to make todo list.", 
        code: "https://github.com/ashokkhandhar/todo-list",
        live: "https://todo-list-wr0k.onrender.com/",
    },
    {
        heading: "Ecommerce App",
        tech: "HTML, CSS, JavaScript",
        description: "Ecommerce cloth shoping app.", 
        code: "https://github.com/ashokkhandhar/ecommerce-app",
        live: "https://ashokkhandhar.github.io/ecommerce-app/",
    },
    {
        heading: "Notes App",
        tech: "HTML, CSS, JavaScript",
        description: "Note taking app.", 
        code: "https://github.com/ashokkhandhar/notes-app",
        live: "https://notes-by-ak.netlify.app/",
    },
    {
        heading: "Wishlist App",
        tech: "HTML, CSS, JavaScript",
        description: "Wishlist is supper cool to add your bucket list, and have stored for life time.", 
        code: "https://github.com/ashokkhandhar/Wishlist-App",
        live: "https://ashokkhandhar.github.io/Wishlist-App/",
    },
    {
        heading: "Symon Game",
        tech: "HTML, CSS, JavaScript",
        description: "A web game for increase brain power.", 
        code: "https://github.com/ashokkhandhar/Simon-Game",
        live: "https://ashokkhandhar.github.io/Simon-Game/",
    },
    {
        heading: "Random dice generator",
        tech: "HTML, CSS, JavaScript",
        description: "Generate dice randomly and declare the winner.", 
        code: "https://github.com/ashokkhandhar/random-dice-generator",
        live: "https://ashokkhandhar.github.io/random-dice-generator/",
    },
    {
        heading: "Pricing Table",
        tech: "HTML, CSS, JavaScript",
        description: "Pricing cards Design, implemented dark and light theme", 
        code: "https://github.com/ashokkhandhar/pricing-table",
        live: "https://ashokkhandhar.github.io/pricing-table/",
    },
    {
        heading: "Form Validation",
        tech: "HTML, CSS, JavaScript",
        description: "Login-Reginstration form validation using regular expression", 
        code: "https://github.com/ashokkhandhar/Form-Validation",
        live: "https://ashokkhandhar.github.io/Form-Validation/",
    },
    {
        heading: "Drum Player",
        tech: "HTML, CSS, JavaScript",
        description: "Web page to play drums virtyally", 
        code: "https://github.com/ashokkhandhar/Drum-Player",
        live: "https://ashokkhandhar.github.io/Drum-Player/",
    },
    {
        heading: "Power House",
        tech: "HTML, CSS",
        description: "Frontend Design", 
        code: "https://github.com/ashokkhandhar/power_house",
        live: "https://ashokkhandhar.github.io/power_house/index.html",
    },
    {
        heading: "Counter",
        tech: "HTML, CSS, JavaScript",
        description: "Web page to do count", 
        code: "https://github.com/ashokkhandhar/counter",
        live: "https://ashokkhandhar.github.io/counter/",
    },
    {
        heading: "Math expression Calculator",
        tech: "HTML, JavaScript",
        description: "It's takes and mathamatical expression and give the answer.", 
        code: "https://github.com/ashokkhandhar/Calculater",
        live: "https://ashokkhandhar.github.io/Calculater/",
    },
    {
        heading: "CLI Quiz Application",
        tech: "JavaScript",
        description: "Play quiz on command line interface and view your score on leader board", 
        code: "https://github.com/ashokkhandhar/CLI-Quiz-App",
        live: "",
    },
    {
        heading: "QR code generator",
        tech: "JavaScript",
        description: "Generate QR code for given URL", 
        code: "https://github.com/ashokkhandhar/QR-Code-Generator",
        live: "",
    },
    {
        heading: "Tic Tac Toe - cpp",
        tech: "C++, File handling, OOPs",
        description: "It's Command line tic tac toe game.", 
        code: "https://github.com/ashokkhandhar/tic-tac-toe-CPP",
        live: "",
    },
    {
        heading: "CLI Calculator CPP",
        tech: "C++, File handling, OOPs",
        description: "It's takes and mathamatical expression and give the answer.", 
        code: "https://github.com/ashokkhandhar/Calculator-CPP",
        live: "",
    },
    {
        heading: "Banking System",
        tech: "C++, File handling, OOPs",
        description: "Built a project that shows the basic functionality of Banking-system.", 
        code: "https://github.com/ashokkhandhar/Banking-System",
        live: "",
    },
];